set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_EXECUTABLE_L_FLAGS)
if(NOT MSVC)
    if(OPTION_TARGET_ARCH STREQUAL "x86")
        set(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_EXECUTABLE_L_FLAGS} ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_EXECUTABLE_L_FLAGS}
            -m32)
    elseif(OPTION_TARGET_ARCH STREQUAL "x64")
        set(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_EXECUTABLE_L_FLAGS} ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_EXECUTABLE_L_FLAGS}
            -m64)
    endif()
endif()

target_link_options(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_COMPILE_OPTIONS} INTERFACE 
    $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>: ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_EXECUTABLE_L_FLAGS}>)