set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS)
if(MSVC)
    set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS} 
		/WX
		/W4
		/permissive)
else()
    set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS}
        -Wall 
        -Wextra 
        -Werror
        -fvisibility=hidden
		-Wnoexcept)
    
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS}
            -ggdb)
    endif()

    if(OPTION_TARGET_ARCH STREQUAL "x86")
        set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS}
            -m32)
    elseif(OPTION_TARGET_ARCH STREQUAL "x86_64")
        set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS}
            -m64)
    endif()
endif()

target_compile_options(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_COMPILE_OPTIONS} INTERFACE 
	$<$<COMPILE_LANGUAGE:CXX>: ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_FLAGS}>)

set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_DEFINES)
if(WIN32)
    set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_C_DEFINES ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_C_DEFINES} 
        @OPTION_PROJECT_PREFIX_UPPER_CASE@_WINDOWS)
    set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_DEFINES ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_DEFINES} 
        @OPTION_PROJECT_PREFIX_UPPER_CASE@_WINDOWS)
else()
    set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_C_DEFINES ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_C_DEFINES} 
        @OPTION_PROJECT_PREFIX_UPPER_CASE@_LINUX)
    set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_DEFINES ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_DEFINES} 
        @OPTION_PROJECT_PREFIX_UPPER_CASE@_LINUX)
endif()

target_compile_definitions(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_COMPILE_OPTIONS} INTERFACE 
    $<$<COMPILE_LANGUAGE:CXX>: ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_CXX_DEFINES}>)