set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_STATIC_L_FLAGS)
if(NOT MSVC)
    if(OPTION_TARGET_ARCH STREQUAL "x86")
        set(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_STATIC_L_FLAGS} ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_STATIC_L_FLAGS}
            -m elf_i386)
    elseif(OPTION_TARGET_ARCH STREQUAL "x64")
        set(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_STATIC_L_FLAGS} ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_STATIC_L_FLAGS}
            -m elf_x86_64)
    endif()
endif()

target_link_options(${@OPTION_PROJECT_PREFIX_UPPER_CASE@_COMPILE_OPTIONS} INTERFACE 
    $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,STATIC_LIBRARY>: ${@OPTION_PROJECT_PREFIX_UPPER_CASE@_STATIC_L_FLAGS}>)