# Общая информация
if(WIN32)
	set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_PROJECT_NAME "@OPTION_PROJECT_NAME_CAMEL_CASE@")
else()
	set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_PROJECT_NAME "@OPTION_PROJECT_NAME_SNAKE_CASE@")
endif()

set(@OPTION_PROJECT_PREFIX_UPPER_CASE@_COMPANY_NAME TNLab)
